name: Autograding Tests
'on':
  push:
    paths:
      - "app/**"
      - "public/**"
      - "resources/**"
      - "routes/**"
      - "tests/**"
      - "config/**"
  workflow_dispatch:

env:
  # test-NNNNNN: ランダムな数字6桁を付けて重複を回避させる
  project_name: test-${{ github.run_id }}
  LANG: ja_JP.UTF-8
  CONTAINE_USER: vscode
  ARTIFACTS: 42
  ARTIFACTS_DIR: 42

permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: SECRETから.envファイルを作成
      # actの環境ではスキップしてよい
      if: ${{ !env.ACT }}
      run: |
        # GH SecretのDOTENV変数に.envがまるのまま入っているのでリダイレクトで作成する
        echo "${{ secrets.DOTENV }}" > dot.env
        # dot.envのファイルサイズが10バイト以下の場合、DOTENV secretが無いとみなしてエラーとする　
        if [ $(wc -c < dot.env) -le 10 ]; then
          echo "GitHub SecretのDOTENVが未定義のようです、 Settings > Secrets and Variables > Actions にて作成してください"
          exit 1
        fi
        mv dot.env .env
    - name: .envファイルの存在チェック
      run: |
        if [ ! -f .env ]; then
          echo ".envファイルが存在しません"
          exit 1
        fi
    - name: コンテナの起動
      run: docker compose -p ${{ env.project_name }} -f compose.yml -f compose_test.yml up -d --quiet-pull
    - name: 結果画像の削除
      run: |
        rm -vf results/*.png
    - name: リポジトリの所有者を変更
      if: ${{ !env.ACT }}
      run: |
        docker compose -p ${{ env.project_name }} exec app sudo chown -R ${{ env.CONTAINE_USER }} /app

    - name: データベースへの接続テスト
      id: dbcheck
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: dbcheck
        setup-command: 'docker compose ps'
        command: 'docker compose  -p ${{ env.project_name }} exec app make test FILE=tests/test_db_connect.py'
        max-score: 1
        timeout: 2
    - name: トップページの表示テスト
      id: toppage
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: toppage
        command: 'docker compose -p ${{ env.project_name }} exec app make test FILE=tests/test_minishop_toppage.py'
        max-score: 1
        timeout: 2
    # - name: 結果画像の場所確認
    #   if: always()
    #   run: |
    #     find `pwd` -type f | sort

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DBCHECK_RESULTS: "${{steps.dbcheck.outputs.result}}"
        TOPPAGE_RESULTS: "${{steps.toppage.outputs.result}}"
      with:
        runners: dbcheck,toppage

    - name: アーティファクト置場の確認
      run: |
        # もしact環境なら、カレントディレクトリ上にartifactsディレクトリを作成
        # このパスをGITHUB_ENVに追加する
        # github actionsであれば、~/artifactsにアーティファクトを保存
        # 同様にGITHUB_ENVに追加する
        if [ -n "$ACT" ]; then
          mkdir -p ./artifacts-${{ env.project_name }}
          echo ARTIFACTS_DIR=./artifacts-${{ env.project_name }} >> $GITHUB_ENV
        else
          mkdir -p ~/artifacts-${{ env.project_name }}
          echo ARTIFACTS_DIR=$HOME/artifacts-${{ env.project_name }} >> $GITHUB_ENV
        fi
    - name: 結果画像の一覧作成
      run: |
        docker compose -p ${{ env.project_name }} cp app:/app/results ${{ env.ARTIFACTS_DIR }}
        echo ARTIFACTS=$(find  ${{ env.ARTIFACTS_DIR }} -name "*.png") >> $GITHUB_ENV
    - name: 画像ファイルのアーティファクト化
      if: always() && env.ARTIFACTS != ''
      uses: actions/upload-artifact@v4
      with:
        name: result-images
        path: |
          ${{ env.ARTIFACTS }}
    - name: アーティファクトのディレクトリを削除しておく
      if: always()
      run: rm -rf ${{ env.ARTIFACTS_DIR }}
    - name: コンテナの停止
      if: always()
      run: docker compose  -p ${{ env.project_name }} down --rmi=local -v --timeout=3
    # - name: check files
    #   if: always()
    #   run: pwd; ls -l results
